version: '3.1'

services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - 8081:27017
        volumes:
            - .dbdata:/data/db
    passport_key_server:
        build: .
        depends_on:
            - mongo
        ports:
            - 8080:8080
        volumes:
            - .env:/app/.env
